name: A worlflow for my Hello World file
on: push
jobs:
  name: Hello world action
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - uses: ./action-a
      with:
        MY_NAME: "Mona"

